import requests
import json

# ===================== CONFIGURATION =====================
API_URL = "https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-Instruct-v0.1"
headers = {"Authorization": "Bearer hf_your_token_here"}  # replace with your Hugging Face token

# ===================== INPUT STRUCTURE =====================
# Example structure your Excel-to-PPT tool may produce after data extraction
structure = {
    "presentation_title": "Business Intelligence Report: Hotel Bookings Analysis",
    "slides": [
        {
            "type": "description",
            "title": "Overview",
            "content": "This presentation summarizes the insights extracted from the hotel bookings dataset including cancellation rates, lead times, and customer segments."
        },
        {
            "type": "chart",
            "title": "Cancellation Analysis",
            "content": "Shows percentage of canceled vs confirmed bookings based on lead time and market segment.",
            "chart_data": {"type": "bar", "x": "lead_time", "y": "is_canceled"}
        },
        {
            "type": "chart_insight",
            "title": "Insights on Cancellations",
            "content": "Longer lead times tend to have higher cancellation rates, especially among online travel agency customers."
        },
        {
            "type": "dashboard",
            "title": "Booking Overview Dashboard",
            "content": "Combines metrics such as total bookings, average daily rate, and country-wise distribution."
        },
        {
            "type": "query_table",
            "title": "Top 5 Countries by Booking Volume",
            "content": "Displays a table of the top 5 countries contributing to hotel bookings along with their average ADR."
        },
        {
            "type": "conclusion",
            "title": "Business Recommendations",
            "content": "Reduce dependency on online travel agencies and provide discounts for longer-stay customers to reduce cancellations."
        }
    ]
}

# ===================== PROMPT DESIGN =====================
prompt = f"""
You are a presentation generation expert and business data storyteller.

Below is the structured input for a PowerPoint presentation generated from data analysis:
{json.dumps(structure, indent=2)}

Your task:
1. Analyze all slide types and enhance their content professionally.
2. For 'description' slides → rewrite text to be engaging and business-focused.
3. For 'chart' slides → explain what the chart shows, suggest better visualization options if needed.
4. For 'chart_insight' slides → turn them into crisp business insights and add one recommendation.
5. For 'dashboard' slides → enhance with KPIs and visual design suggestions (cards, infographics, etc.).
6. For 'query_table' slides → summarize what the table reveals and suggest a possible action or observation.
7. For 'conclusion' slides → summarize findings and business recommendations in bullet format.
8. For every slide, add a "visual_suggestion" section with what visuals to include (flowchart, pie chart, KPI cards, icons, etc.).

Output in strict JSON format:
{
  "enhanced_title": "Improved Presentation Title",
  "slides": [
    {
      "type": "slide_type",
      "title": "Slide Title",
      "enhanced_text": ["point1", "point2", ...],
      "visual_suggestion": "Suggestions for visual layout or chart design"
    }
  ]
}
"""

# ===================== API CALL =====================
response = requests.post(API_URL, headers=headers, json={"inputs": prompt})
result = response.json()

# ===================== OUTPUT =====================
print("\n======= ENHANCED PPT STRUCTURE GENERATED BY LLM =======\n")
print(json.dumps(result, indent=2))

